name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # 1. GitHub 코드 체크아웃
    - name: Checkout source code
      uses: actions/checkout@v4

    # 2. JDK 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Gradle 설정
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # 4. gradlew 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # 5. 프로젝트 빌드
    - name: Build with Gradle
      run: ./gradlew build

    # 6. JAR 파일 서버에 복사
    - name: Copy JAR to remote server
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem -P ${{ secrets.PORT }} ./build/libs/*.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/cicd/

    # 7. deploy.sh 서버에 복사
    - name: Copy deploy.sh to remote server
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem -P ${{ secrets.PORT }} ./deploy.sh ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/cicd/

    # 8. 서버에서 deploy.sh 실행
    - name: Run deploy script on remote server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          chmod +x /root/cicd/deploy.sh
          /root/cicd/deploy.sh
